<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HashtagChris.DotNetBlueZ" Version="1.3.1" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program_CLI.cs" />
    <Compile Include="src/CLI/CLI_UTILMAN.cs" />
	  <Compile Include="src/CLI/BrightnessService.cs" />
	  <Compile Include="src/CLI/VolumeService.cs" />
	  <Compile Include="src/CLI/BatteryService.cs" />
	  <Compile Include="src/CLI/BluetoothService.cs" />
	  <Compile Include="src/CLI/WifiService.cs" />
	  <Compile Include="src/CLI/ServicesService.cs" />
	  <Compile Include="src/CLI/PackageService.cs" />
	  <Compile Include="src/CLI/LogService.cs" />
	  <Compile Include="src/CLI/FirewallService.cs" />
	  <Compile Include="src/CLI/StatusService.cs" />
	  <Compile Include="src/CLI/SystemMonitoringService.cs" />
	  <Compile Include="src/CLI/UserService.cs" />
	  <Compile Include="src/CLI/PowerService.cs" />
    <Compile Include="src/CLI/Help.cs" />
    <Compile Include="src/CLI/MenuEngine.cs" />
    <Compile Include="src/Shared/Terminal.cs" />
    <Compile Include="src/Shared/Models.cs" />
    <Compile Include="src/DownloadScript.cs" />
  </ItemGroup>
</Project>
